services:
  archipelago:
    build: .
    container_name: archipelago
    network_mode: host
    environment:
      - ARCHIPELAGO_PASSWORD
      - ARCHIPELAGO_SSH_USER
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ./data:/data
    restart: unless-stopped
